# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit.xci
# IP: The module: 'ram_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_8bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit.xci
# IP: The module: 'ram_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
