# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Homeworks/cpu31real/cpupip31real/cpupip31real.cache/wt [current_project]
set_property parent.project_path E:/Homeworks/cpu31real/cpupip31real/cpupip31real.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/Homeworks/cpu31real/tests/test.coe
add_files -quiet E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.dcp]
add_files -quiet e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit.dcp
set_property used_in_implementation false [get_files e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/ram_8bit/ram_8bit.dcp]
read_verilog E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mips_def.vh
read_verilog -library xil_defaultlib {
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mux2_32.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/register.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/regfile.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mux8_32.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mux4_32.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mux2_5.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/mult.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/forwarding.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/dmem.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/div.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/cutter.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/cp0.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/controller.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/compare.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/clz_counter.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/alu.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/IMEM_ip.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_wb.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_mem_wb.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_mem.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_if_id.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_if.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_id_ex.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_id.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_ex_mem.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pipe_ex.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/pc.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/seg7x16.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/cpu.v
  E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/new/board_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/constrs_1/new/xdc.xdc]


synth_design -top board_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef board_top.dcp

catch { report_utilization -file board_top_utilization_synth.rpt -pb board_top_utilization_synth.pb }
