# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
