# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Homeworks/cpu31real/cpupip31real/cpupip31real.cache/wt [current_project]
set_property parent.project_path E:/Homeworks/cpu31real/cpupip31real/cpupip31real.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.xci
set_property is_locked true [get_files E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top imem -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all imem_

write_checkpoint -force -noxdef imem.dcp

catch { report_utilization -file imem_utilization_synth.rpt -pb imem_utilization_synth.pb }

if { [catch {
  file copy -force E:/Homeworks/cpu31real/cpupip31real/cpupip31real.runs/imem_synth_1/imem.dcp E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir E:/Homeworks/cpu31real/cpupip31real/cpupip31real.ip_user_files/ip/imem]} {
  catch { 
    file copy -force E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_stub.v E:/Homeworks/cpu31real/cpupip31real/cpupip31real.ip_user_files/ip/imem
  }
}

if {[file isdir E:/Homeworks/cpu31real/cpupip31real/cpupip31real.ip_user_files/ip/imem]} {
  catch { 
    file copy -force E:/Homeworks/cpu31real/cpupip31real/cpupip31real.srcs/sources_1/ip/imem/imem_stub.vhdl E:/Homeworks/cpu31real/cpupip31real/cpupip31real.ip_user_files/ip/imem
  }
}
